// src/renderer/src/App.vue
<script setup lang="ts">
import { onMounted, onUnmounted, ref } from "vue";
import { FilePayload } from "@/types";
import log from "electron-log/renderer";
import MainWindow from "@components/MainWindow.vue";
import Sidebar from "@components/Sidebar.vue";
import { storeToRefs } from "pinia";
import Topbar from "@components/Topbar.vue";
import { useAudio } from "@stores/audio";

const audioStore = useAudio();
const { audio } = storeToRefs(audioStore);
const { setAudio } = audioStore;
const audioElement = ref<HTMLAudioElement | null>(null);
const audioSrc = ref("");

function playAudio() {
  if (audio.value) {
    if (audioSrc.value !== "") {
      audio.value.load();
      audio.value.play().catch((error) => {
        log.error("Failed to play audio", error);
      });
    }
    else {
      log.error("Audio source is empty");
    }
  }
}

function handleFileOpen(_event: Electron.IpcRendererEvent, file: FilePayload, play: boolean) {
  audioSrc.value = URL.createObjectURL(new Blob([file.uint8Array], { type: "audio/mpeg" }));
  if (play) {
    playAudio();
  }
}

onMounted(() => {
  setAudio(audioElement.value!);
  window.api.on("open-file", handleFileOpen);
});

onUnmounted(() => {
  window.api.off("open-file", handleFileOpen);
});

</script>

<template>
  <audio ref="audioElement" :src="audioSrc" preload="none" :controls="false" />
  <div
    class="relative grid w-full h-full min-h-full overflow-y-hidden grid-areas-layout grid-rows-layout grid-cols-layout">
    <Topbar class="z-10 flex flex-row items-center w-full h-16 m-0 grid-in-main-view justify-evenly" />
    <Sidebar class="z-20 w-56 m-0 text-gray-800 grid-in-nav-bar bg-gray-150 dark:bg-gray-900 dark:text-white" />
    <MainWindow class="flex flex-col w-full overflow-hidden grid-in-main-view bg-gray-180 dark:bg-gray-860" />
  </div>
</template>

// src/renderer/src/App.tsx
import React from "react";
import MainWindow from "./components/MainWindow";
import MediaControlsBar from "./components/MediaControlsBar";
import Sidebar from "./components/Sidebar";
import Topbar from "./components/Topbar";
import { FilePayload } from "@/types";

function App() {
  const [expanded, setExpanded] = React.useState(false);
  const [src, setSrc] = React.useState("");
  const audio = React.useRef<HTMLAudioElement>(null);
  const requestedPlay = React.useRef(false);

  const handleFileOpen = (_event: Electron.IpcRendererEvent, file: FilePayload, play: boolean): void => {
    const blob = new Blob([file.uint8Array], { type: "audio/mpeg" });
    const url = URL.createObjectURL(blob);
    setSrc(url);
    requestedPlay.current = play;
  };

  React.useEffect(() => {
    window.api.onFileOpen(handleFileOpen);
    return () => {
      window.api.offFileOpen(handleFileOpen);
    };
  });

  React.useEffect(() => {
    const playAudioPromise = (): void => {
      if (src === "") {
        console.log("No src");
        return;
      }
      const aud = audio.current;
      if (!aud) {
        return;
      }
      aud.load();
      const playPromise = aud.play();
      // playPromise is null in IE 11
      playPromise.then(null).catch((err) => {
        console.log(err);
      });
    };
    if (audio.current && requestedPlay.current) {
      playAudioPromise();
      requestedPlay.current = false;
    }
  }, [audio, src, requestedPlay]);

  const expandSongDetails = () => {
    console.log("Expand song details");
    setExpanded(!expanded);
  };

  return (
    <>
      <audio controls={false} preload="false" ref={audio} src={src} />
      <div className="relative grid overflow-y-hidden h-full min-h-full w-full grid-areas-layout grid-rows-layout grid-cols-layout">
        <Topbar className="grid-in-main-view z-10 m-0 h-16 w-full flex flex-row items-center justify-evenly" />
        <Sidebar className="z-20 m-0 w-56 grid-in-nav-bar bg-gray-150 text-gray-800 dark:bg-gray-900 dark:text-white" />
        <MediaControlsBar
          audio={audio}
          className="grid-in-now-playing z-30 h-[90px] w-full bg-gray-220 dark:bg-gray-880 px-4"
          expandFunc={expandSongDetails}
        />
        <MainWindow
          audio={audio}
          className="grid-in-main-view flex flex-col overflow-hidden w-full bg-gray-180 dark:bg-gray-860"
        />
      </div>
    </>
  );
}
export default App;
