// client/src/renderer/src/components/MediaControlsBar/MediaControls/SkipForwardButton/SkipForwardButton.tsx
import React from "react";
import { ReactComponent as SkipForwardIcon } from "@/assets/icons/skip_forward.svg";

interface SkipForwardButtonProps {
  skipForward?: (e: React.SyntheticEvent) => void;
  audio?: HTMLAudioElement | null;
}

export default function SkipForwardButton({ skipForward, audio }: SkipForwardButtonProps): JSX.Element {
  const isAudioAvailable = React.useMemo(() => audio && audio.src !== "", [audio]);
  return isAudioAvailable ? (
    <div className="h-8 aspect-square flex justify-center items-center" onClick={skipForward}>
      <SkipForwardIcon className="m-0 w-4 h-4 transition-all duration-300 ease-in-out non-scale-stroke fill-gray-600 hover:fill-gray-550 dark:fill-gray-500 hover:dark:fill-gray-350" />
    </div>
  ) : (
    <div className="h-8 aspect-square flex justify-center items-center">
      <SkipForwardIcon className="m-0 w-4 h-4 fill-gray-450 dark:fill-gray-550" />
    </div>
  );
}

// src/renderer/src/components/media-controls/SkipForwardButton.vue
<script setup lang="ts">
import SkipForwardIcon from "@icons/next.svg";
import { storeToRefs } from "pinia";
import { useAudio } from "@stores/audio";

const { isAudioAvailable } = storeToRefs(useAudio());
const { getNextSong } = useAudio();
</script>

<template>
  <div
    v-if="isAudioAvailable"
    class="flex items-center justify-center h-8 aspect-square"
    @click="getNextSong"
  >
    <SkipForwardIcon
      class="w-4 h-4 m-0 transition-all duration-300 ease-in-out non-scale-stroke fill-gray-750 hover:fill-gray-600 dark:fill-gray-300 hover:dark:fill-gray-150"
    />
  </div>
  <div
    v-else
    class="flex items-center justify-center h-8 aspect-square"
  >
    <SkipForwardIcon class="w-4 h-4 m-0 fill-gray-350 dark:fill-gray-750" />
  </div>
</template>
