// client/src/renderer/src/components/MediaControlsBar/MediaControls/SkipBackButton/SkipBackButton.tsx
import React from "react";
import { ReactComponent as SkipBackwardIcon } from "@/assets/icons/skip_backward.svg";

interface SkipBackButtonProps {
  skipBack?: (e: React.SyntheticEvent) => void;
  audio?: HTMLAudioElement | null;
}

export default function SkipBackButton({ skipBack, audio }: SkipBackButtonProps): JSX.Element {
  const isAudioAvailable = React.useMemo(() => audio && audio.src !== "", [audio]);
  return isAudioAvailable ? (
    <div className="h-8 aspect-square flex justify-center items-center" onClick={skipBack}>
      <SkipBackwardIcon className="m-0 w-4 h-4 transition-all duration-300 ease-in-out non-scale-stroke fill-gray-600 hover:fill-gray-550 dark:fill-gray-500 hover:dark:fill-gray-350" />
    </div>
  ) : (
    <div className="h-8 aspect-square flex justify-center items-center">
      <SkipBackwardIcon className="m-0 w-4 h-4 fill-gray-450 dark:fill-gray-550" />
    </div>
  );
}

// src/renderer/src/components/media-controls/SkipBackButton.vue
<script setup lang="ts">
import SkipBackIcon from "@icons/previous.svg";
import { storeToRefs } from "pinia";
import { useAudio } from "@stores/audio";

const { isAudioAvailable } = storeToRefs(useAudio());
const { skipPrevious } = useAudio();
</script>

<template>
  <div
    v-if="isAudioAvailable"
    class="flex items-center justify-center h-8 aspect-square"
    @click="skipPrevious"
  >
    <SkipBackIcon
      class="w-4 h-4 m-0 transition-all duration-300 ease-in-out non-scale-stroke fill-gray-750 hover:fill-gray-600 dark:fill-gray-300 hover:dark:fill-gray-150"
    />
  </div>
  <div
    v-else
    class="flex items-center justify-center h-8 aspect-square"
  >
    <SkipBackIcon class="w-4 h-4 m-0 fill-gray-350 dark:fill-gray-750" />
  </div>
</template>
