// src/renderer/src/components/cards/ImageCard.vue
<script setup lang="ts">

const props = defineProps<{
  src: string;
  line1: string;
  line2: string;
  loading?: "lazy" | "eager";
  onClickButton?:() => void;
  onClickCard?: () => void;
}>();

</script>

<template>
  <div
    className="bg-gray-250 dark:bg-gray-800 group isolate relative w-full p-4 hover:bg-gray-300 hover:dark:bg-gray-750 transition-[background-color] duration-300 ease-[ease]"
    style="--card-container-border-radius: clamp(4px,(var(--column-width,0px) - 32px) * 0.025,8px); border-radius: calc(var(--card-container-border-radius) + 2px);"
  >
    <div class-="h-full select-none">
      <div className="mb-4 relative">
        <div
          class="relative pb-[100%] bg-gray-350 dark:bg-gray-750"
          style="--card-image-border-radius: clamp(4px,(var(--column-width,0px) - 32px) * 0.025,8px); border-radius: var(--card-image-border-radius); box-shadow: 0 8px 24px rgb(0 0 0 / 50%);"
        >
          <img
            class="absolute top-0 left-0 object-cover w-full h-full animate-imageFadeInAnimation"
            :loading="props.loading || 'lazy'"
            :src="props.src"
            style="animation-fill-mode: forwards; animation-iteration-count: 1; --card-image-border-radius: clamp(4px,(var(--column-width,0px) - 32px) * 0.025,8px); border-radius: var(--card-image-border-radius); object-position: center center;"
          >
        </div>
        <div v-if="props.onClickButton">
          <div
            class="bottom-2 right-2 rounded-full z-[2] opacity-0 pointer-events-none absolute transition-all duration-300 ease-[ease] translate-y-2 group-hover:pointer-events-auto group-hover:opacity-100 group-hover:translate-y-0 outline-nothing"
            style="box-shadow: 0 8px 8px rgb(0 0 0 / 30%);"
          >
            <button
              class="relative z-[1] transition-[background-color, border-color, color, box-shadow, filter, transform] select-none touch-manipulation block duration-[33ms] group/button cursor-default outline-nothing"
              @click="props.onClickButton"
            >
              <slot name="icon" />
            </button>
          </div>
        </div>
      </div>
      <div className="min-h-[62px]">
        <a
          class="relative z-[1] inline-block w-full align-middle select-none touch-manipulation cursor-pointer"
          :title="line1"
        >
          <div
            class="box-border overflow-hidden text-base font-bold text-gray-800 text-ellipsis whitespace-nowrap dark:text-gray-100"
            style="margin-block: 0px; padding-block-end: 4px;"
          >
            {{ props.line1 }}
          </div>
        </a>
        <div
          class="text-[0.8125rem] md:text-sm box-border font-normal text-gray-700 dark:text-gray-300 overflow-hidden mt-1 text-ellipsis whitespace-nowrap"
          style="margin-block: 0px;"
        >
          <span>{{ props.line2 }}</span>
        </div>
      </div>
      <div
        class="absolute top-0 bottom-0 left-0 right-0 z-0 overflow-hidden cursor-pointer"
        @click="props.onClickCard"
      />
    </div>
  </div>
</template>

// client/src/renderer/src/components/ImageCard/ImageCard.tsx
import React from "react";

type ImageCardProps = {
  src: string;
  line1: string;
  line2: string;
  loading?: "lazy" | "eager";
  onClickButton?: () => void;
  onClickCard?: () => void;
  icon?: React.ReactNode;
};

interface CustomCSSProperties extends React.CSSProperties {
  "--card-container-border-radius"?: number | string;
  "--card-image-border-radius"?: number | string;
}

export function ImageCardSkeleton() {
  return (
    <div
      className="bg-gray-400 dark:bg-gray-700 group isolate relative w-full p-4 hover:bg-gray-450 hover:dark:bg-gray-600 transition-[background-color] duration-300 ease-[ease]"
      style={
        {
          "--card-container-border-radius": "clamp(4px,(var(--column-width,0px) - 32px) * 0.025,8px)",
          borderRadius: "calc(var(--card-container-border-radius) + 2px)",
        } as CustomCSSProperties
      }
    >
      <div className="h-full select-none">
        <div className="mb-4 relative">
          <div
            className="relative pb-[100%]"
            style={
              {
                "--card-image-border-radius": "clamp(4px,(var(--column-width,0px) - 32px) * 0.025,8px)",
                borderRadius: "var(--card-image-border-radius)",
                boxShadow: "0 8px 24px rgb(0 0 0 / 50%)",
              } as CustomCSSProperties
            }
          >
            <div
              className="absolute top-0 left-0 h-full w-full bg-gray-400 dark:bg-gray-600 animate-pulse"
              style={
                {
                  "--card-image-border-radius": "clamp(4px,(var(--column-width,0px) - 32px) * 0.025,8px)",
                  borderRadius: "var(--card-image-border-radius)",
                } as CustomCSSProperties
              }
            />
          </div>
        </div>
        <div className="flex flex-col justify-center">
          <div className="w-full h-5 rounded-full bg-gray-400 dark:bg-gray-600 animate-pulse" />
          <div className="w-2/3 h-4 rounded-full bg-gray-400 dark:bg-gray-600 animate-pulse mt-2" />
        </div>
      </div>
    </div>
  );
}

export default function ImageCard({ src, line1, line2, loading, onClickButton, icon, onClickCard }: ImageCardProps) {
  return (
    <div
      className="bg-gray-400 dark:bg-gray-700 group isolate relative w-full p-4 hover:bg-gray-450 hover:dark:bg-gray-600 transition-[background-color] duration-300 ease-[ease]"
      style={
        {
          "--card-container-border-radius": "clamp(4px,(var(--column-width,0px) - 32px) * 0.025,8px)",
          borderRadius: "calc(var(--card-container-border-radius) + 2px)",
        } as CustomCSSProperties
      }
    >
      <div className="h-full select-none">
        <div className="mb-4 relative">
          <div
            className="relative pb-[100%] bg-gray-400 dark:bg-gray-600"
            style={
              {
                "--card-image-border-radius": "clamp(4px,(var(--column-width,0px) - 32px) * 0.025,8px)",
                borderRadius: "var(--card-image-border-radius)",
                boxShadow: "0 8px 24px rgb(0 0 0 / 50%)",
              } as CustomCSSProperties
            }
          >
            <img
              className="h-full w-full absolute top-0 left-0 object-cover animate-imageFadeInAnimation"
              loading={loading || "lazy"}
              src={src}
              style={
                {
                  animationFillMode: "forwards",
                  animationIterationCount: "1",
                  "--card-image-border-radius": "clamp(4px,(var(--column-width,0px) - 32px) * 0.025,8px)",
                  borderRadius: "var(--card-image-border-radius)",
                  objectPosition: "center center",
                } as CustomCSSProperties
              }
            />
          </div>
          {onClickButton
            ? (
              <div
                className="bottom-2 right-2 rounded-full z-[2] opacity-0 pointer-events-none absolute transition-all duration-300 ease-[ease] translate-y-2 group-hover:pointer-events-auto group-hover:opacity-100 group-hover:translate-y-0"
                style={{
                  boxShadow: "0 8px 8px rgb(0 0 0 / 30%)",
                }}
              >
                <button
                  className="relative z-[1] transition-[background-color, border-color, color, box-shadow, filter, transform] select-none touch-manipulation inline-block duration-[33ms] group/button cursor-default"
                  onClick={onClickButton}
                >
                  {icon}
                </button>
              </div>
            )
            : (
              <></>
            )}
        </div>
        <div className="min-h-[62px]">
          <a
            className="relative z-[1] inline-block w-full align-middle select-none touch-manipulation cursor-pointer"
            title={line1}
          >
            <div
              className="box-border overflow-hidden text-ellipsis whitespace-nowrap font-bold text-base text-gray-800 dark:text-gray-100"
              style={{
                marginBlock: "0px",
                paddingBlockEnd: "4px",
              }}
            >
              {line1}
            </div>
          </a>
          <div
            className="text-[0.8125rem] md:text-sm box-border font-normal text-gray-550 dark:text-gray-450 overflow-hidden mt-1 text-ellipsis "
            style={{
              marginBlock: "0px",
            }}
          >
            <span>{line2}</span>
          </div>
        </div>
        <div
          className="absolute z-0 bottom-0 top-0 left-0 right-0 overflow-hidden cursor-pointer"
          onClick={onClickCard}
        />
      </div>
    </div>
  );
}
