// src/renderer/src/components/media-controls/RepeatButton.vue
<script setup lang="ts">
import RepeatAllIcon from "@icons/repeat_all.svg";
import { RepeatMode } from "@/types";
import RepeatOnceIcon from "@icons/repeat_once.svg";
import { storeToRefs } from "pinia";
import { useAudio } from "@stores/audio";

const { repeatMode } = storeToRefs(useAudio());
const { incrementRepeatMode } = useAudio();
</script>

<template>
  <div
    class="flex items-center justify-center h-8 aspect-square"
    @click="incrementRepeatMode"
  >
    <RepeatAllIcon
      v-if="repeatMode === RepeatMode.ALL"
      id="repeat-all"
      class="w-4 h-4 m-0 transition-all duration-300 ease-in-out fill-green-700 hover:fill-green-800 dark:fill-green-600 hover:dark:fill-green-700"
    />
    <RepeatOnceIcon
      v-else-if="repeatMode === RepeatMode.ONCE"
      id="repeat-once"
      class="w-4 h-4 m-0 transition-all duration-300 ease-in-out fill-green-700 hover:fill-green-800 dark:fill-green-600 hover:dark:fill-green-700"
    />
    <RepeatAllIcon
      v-else
      id="repeat-none"
      class="w-4 h-4 m-0 transition-all duration-300 ease-in-out non-scale-stroke fill-gray-750 hover:fill-gray-600 dark:fill-gray-300 hover:dark:fill-gray-150"
    />
  </div>
</template>

// client/src/components/MediaControlsBar/MediaControls/RepeatButton/index.tsx
import React, { useState } from "react";
import { ReactComponent as LoopIcon } from "../../../../assets/icons/loop.svg";
import { ReactComponent as LoopOnceIcon } from "../../../../assets/icons/loop_once.svg";

export default function RepeatButton() {
  const [repeat, setRepeat] = useState(0);
  const handleRepeat = () => {
    if (repeat === 2) {
      setRepeat(0);
    }
    else {
      setRepeat(repeat + 1);
    }
  };
  return (
    <div
      className="h-8 aspect-square flex justify-center items-center"
      data-testid="repeat-button"
      onClick={() => handleRepeat()}
    >
      {repeat === 1
        ? (
          <LoopIcon
            className="m-0 w-4 h-4 cursor-pointer transition-all duration-300 ease-in-out fill-green-450 hover:fill-green-500 dark:fill-green-350 hover:dark:fill-green-450"
            data-testid="repeat-icon"
            id="repeat-all"
          />
        )
        : repeat === 2
          ? (
            <LoopOnceIcon
              className="m-0 w-4 h-4 cursor-pointer transition-all duration-300 ease-in-out fill-green-450 hover:fill-green-500 dark:fill-green-350 hover:dark:fill-green-450"
              data-testid="repeat-icon"
              id="repeat-one"
            />
          )
          : (
            <LoopIcon
              className="m-0 w-4 h-4 cursor-pointer fill-gray-450 transition-all duration-300 ease-in-out hover:fill-gray-550 dark:fill-gray-550 hover:dark:fill-gray-150"
              data-testid="repeat-icon"
              id="repeat-none"
            />
          )}
    </div>
  );
}
