// src/renderer/src/components/Settings/SettingsWindow/SettingsWindow.tsx
import { SettingsSection } from "@/types";
import React from "react";
import _ from "lodash";
import SettingsGroup from "../Fields/SettingsGroup";

type SettingsWindowProps = {
  activeSection?: string;
  sections: SettingsSection[];
  preferences: { [key: string]: any };
  onFieldChange: (key: string, value: any) => void;
};

export default class SettingsWindow extends React.Component<SettingsWindowProps> {
  private mainRef: React.RefObject<HTMLDivElement>;
  constructor(props: SettingsWindowProps) {
    super(props);
    this.mainRef = React.createRef();
  }

  componentDidUpdate(prevProps: Readonly<SettingsWindowProps>): void {
    if (this.props.activeSection !== prevProps.activeSection) {
      this.mainRef.current?.scrollTo({ top: 0 });
    }
  }

  render() {
    const { preferences, section, onFieldChange } = this;
    const groups = this.form?.groups.map((group, idx) => (
      <SettingsGroup
        group={group}
        key={idx}
        label={group.label}
        // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment, @typescript-eslint/no-non-null-assertion
        preferences={preferences[section!.id]}
        onFieldChange={onFieldChange}
      />
    ));

    return (
      <div
        className="settings-window h-full min-h-full w-[600px] min-w-[600px] max-w-[600px] p-3 text-sm cursor-default overflow-x-hidden overflow-y-auto"
        ref={this.mainRef}
      >
        {groups}
      </div>
    );
  }

  get preferences() {
    return this.props.preferences;
  }

  get section() {
    return _.find(this.sections, { id: this.activeSection });
  }

  get sections() {
    return this.props.sections;
  }

  get activeSection() {
    return this.props.activeSection;
  }

  get form() {
    return this.section?.form;
  }

  get onFieldChange() {
    return this.props.onFieldChange;
  }
}

// src/renderer/src/components/Settings/SettingsWindow.vue
<script setup lang="ts">
import { computed, ref, watch } from "vue";
import CustomScrollbar from "@components/CustomScrollbar.vue";
import Group from "./fields/Group.vue";
import lodash from "lodash";
import { SettingsSection } from "@/types";

const props = defineProps<{
  activeSection: string;
  sections: SettingsSection[];
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  preferences: { [key: string]: any };
}>();

defineEmits<{
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  fieldChange: [groupKey: string, fieldKey: string, value: any];
}>();

const section = computed(() => lodash.find(props.sections, { id: props.activeSection }) ?? props.sections[0]);
// eslint-disable-next-line @typescript-eslint/no-redundant-type-constituents
const scrollbarRef = ref<InstanceType<typeof CustomScrollbar> | null>(null);

watch(() => props.activeSection, (newValue, oldValue) => {
  if (newValue !== oldValue) {
    if (scrollbarRef.value) {
      // eslint-disable-next-line @typescript-eslint/no-unsafe-member-access
      if (scrollbarRef.value.scrollHost) {
        // eslint-disable-next-line @typescript-eslint/no-unsafe-call, @typescript-eslint/no-unsafe-member-access
        scrollbarRef.value.scrollHost.scrollTo({ top: 0 });
      }
    }
  }
});

</script>

<template>
  <CustomScrollbar
    ref="scrollbarRef"
    class="h-full min-h-full w-4/5 min-w-[500px] text-sm cursor-default"
    scroll-host-class="p-3 overflow-x-hidden overflow-y-auto"
  >
    <Group
      v-for="group in section.form.groups"
      :key="section.id + group.id"
      :preferences="props.preferences[section.id]"
      :group="group"
      :label="group.label"
      @field-change="(fieldKey, value) => $emit('fieldChange', group.id, fieldKey, value)"
    />
  </CustomScrollbar>
</template>
