// src/renderer/src/components/ProgressBar.vue
<script setup lang="ts">
import { onMounted, onUnmounted, ref } from "vue";
import { MediaReadyState } from "@/types";
import { storeToRefs } from "pinia";
import { useAudio } from "@stores/audio";
import { usePositionX } from "@composables/positionX";
import { useThrottle } from "@composables/throttle";

const props = withDefaults(defineProps<{
  progressUpdateInterval?: number;
}>(), {
  progressUpdateInterval: 0,
});

const { getPositionX } = usePositionX();
const { throttle } = useThrottle();

const { audio, readyState, duration, currentTime, isAudioAvailable } = storeToRefs(useAudio());

const progress = ref<HTMLDivElement | null>(null);
const isDragging = ref(false);
const timeOnMouseMove = ref(0);
const currentTimePosition = ref("0.00%");

function getCurrentProgress(event: MouseEvent | TouchEvent) {
  if (!progress.value) {
    return { currentTimeValue: 0, currentTimePositionValue: "0.00%" };
  }
  const { left, width: maxRelativePosition } = progress.value.getBoundingClientRect();

  const relativePosition = Math.min(Math.max(getPositionX(event) - left, 0), maxRelativePosition);
  const currentTimeValue = (duration.value * relativePosition) / maxRelativePosition;
  const currentTimePositionValue = `${((relativePosition / maxRelativePosition) * 100).toFixed(2)}%`;
  return { currentTimeValue, currentTimePositionValue };
}

function handleMouseOrTouchMove(event: MouseEvent | TouchEvent) {
  if (event instanceof MouseEvent) {
    event.preventDefault();
  }
  event.stopPropagation();
  if (!audio.value) {
    return;
  }

  const windowSelection = window.getSelection();
  if (windowSelection && windowSelection.type === "Range") {
    windowSelection.removeAllRanges();
  }
  if (isDragging.value) {
    const { currentTimeValue, currentTimePositionValue } = getCurrentProgress(event);
    timeOnMouseMove.value = currentTimeValue;
    currentTimePosition.value = currentTimePositionValue;
  }
}

function handleMouseOrTouchUp(event: MouseEvent | TouchEvent) {
  event.stopPropagation();
  isDragging.value = false;
  if (!audio) {
    return;
  }
  if (readyState.value === MediaReadyState.HAVE_NOTHING
    || readyState.value === MediaReadyState.HAVE_METADATA
    || !isFinite(timeOnMouseMove.value)) {
    currentTimePosition.value = "0.00%";
  }
  else {
    currentTime.value = timeOnMouseMove.value;
  }
  if (event instanceof MouseEvent) {
    window.removeEventListener("mousemove", handleMouseOrTouchMove);
    window.removeEventListener("mouseup", handleMouseOrTouchUp);
  }
  else {
    window.removeEventListener("touchmove", handleMouseOrTouchMove);
    window.removeEventListener("touchend", handleMouseOrTouchUp);
  }
}

function handleMouseDownOrTouchStart(event: MouseEvent | TouchEvent) {
  event.stopPropagation();
  if (!audio.value) {
    return;
  }
  isDragging.value = true;
  const { currentTimeValue, currentTimePositionValue } = getCurrentProgress(event);
  if (isFinite(currentTimeValue)) {
    timeOnMouseMove.value = currentTimeValue;
    isDragging.value = true;
    currentTimePosition.value = currentTimePositionValue;
    if (event instanceof MouseEvent) {
      window.addEventListener("mousemove", handleMouseOrTouchMove);
      window.addEventListener("mouseup", handleMouseOrTouchUp);
    }
    else {
      window.addEventListener("touchmove", handleMouseOrTouchMove);
      window.addEventListener("touchend", handleMouseOrTouchUp);
    }
  }
}

const handleAudioTimeUpdate = throttle((_event: Event) => {
  if (isDragging.value) {
    return;
  }
  currentTimePosition.value = `${((currentTime.value / duration.value) * 100).toFixed(2)}%`;
}, props.progressUpdateInterval);

onMounted(() => {
  audio.value?.addEventListener("timeupdate", handleAudioTimeUpdate);
});

onUnmounted(() => {
  audio.value?.removeEventListener("timeupdate", handleAudioTimeUpdate);
});

</script>

<template>
  <div
    v-if="isAudioAvailable"
    ref="progress"
    aria-valuemax="100"
    aria-valuemin="0"
    :aria-valuenow="Number(currentTimePosition.split('%')[0])"
    class="flex flex-row items-center justify-center flex-1 w-4/5 h-5 group"
    role="progressbar"
    @mousedown="handleMouseDownOrTouchStart"
    @touchstart="handleMouseDownOrTouchStart"
  >
    <div class="box-border relative w-full h-1 rounded-full bg-gray-350 dark:bg-gray-750 ">
      <div
        class="box-border absolute z-20 rounded-full h-13/4 aspect-square group-hover:scale-100"
        :class="{ 'scale-100': isDragging, 'scale-0': !isDragging }"
        :style="{ 'left': currentTimePosition }"
      >
        <div
          class="absolute h-full w-full top-[calc((50%*-1)+1px)] ml-[calc(50%*-1)] box-border rounded-full group-hover:bg-gray-550 dark:group-hover:bg-gray-250 shadow shadow-gray-800 dark:shadow-gray-250"
          :class="{ 'bg-gray-550 dark:bg-gray-250': isDragging, 'bg-gray-450 dark:bg-gray-600': !isDragging }"
        />
      </div>
      <div
        class="box-border absolute z-10 h-full rounded-full group-hover:bg-green-700 dark:group-hover:bg-green-600"
        :class="{ 'bg-green-700 dark:bg-green-600': isDragging, 'bg-gray-550 dark:bg-gray-250': !isDragging }"
        :style="{ 'width': currentTimePosition }"
      />
    </div>
  </div>
  <div
    ref="progress"
    class="flex flex-row items-center justify-center flex-1 w-4/5 h-5 group"
    role="progressbar"
  >
    <div class="box-border relative w-full h-1 rounded-full bg-gray-350 dark:bg-gray-750">
      <div class="box-border absolute z-10 h-full bg-gray-300 rounded-full dark:bg-gray-600" />
    </div>
  </div>
</template>

// client/src/components/MediaControlsBar/TrackProgress/ProgressBar/index.tsx
import React, { Component, forwardRef } from "react";
import { getPosX, throttle } from "../../../../utils";

interface ProgressBarState {
  isDraggingProgress: boolean;
  currentTimePos?: string;
}

interface ProgressBarForwardRefProps {
  audio: HTMLAudioElement | null;
  progressUpdateInterval?: number;
  srcDuration?: number;
  i18nProgressBar?: string;
}

interface ProgressBarProps extends ProgressBarForwardRefProps {
  progressRef: React.RefObject<HTMLDivElement>;
}

interface TimePosInfo {
  currentTime: number;
  currentTimePos: string;
}
class ProgressBar extends Component<ProgressBarProps, ProgressBarState> {
  audio?: HTMLAudioElement;
  progressUpdateInterval = 0;

  hasAddedAudioEventListener = false;

  timeOnMouseMove = 0;

  state: ProgressBarState = {
    isDraggingProgress: false,
    currentTimePos: "0%",
  };

  getDuration(): number {
    const { audio, srcDuration } = this.props;
    if (!audio) {
      return 0;
    }
    return typeof srcDuration === "undefined" ? audio.duration : srcDuration;
  }

  getCurrentProgress = (event: MouseEvent | React.MouseEvent | TouchEvent | React.TouchEvent): TimePosInfo => {
    const { progressRef } = this.props;
    if (!progressRef.current) {
      return { currentTime: 0, currentTimePos: "0%" };
    }
    const rect = progressRef.current.getBoundingClientRect();
    const maxRelativePos = rect.width;

    let relativePos = getPosX(event) - rect.left;

    if (relativePos < 0) {
      relativePos = 0;
    }
    else if (relativePos > maxRelativePos) {
      relativePos = maxRelativePos;
    }
    const duration = this.getDuration();
    const currentTime = (duration * relativePos) / maxRelativePos;
    const currentTimePos = `${((relativePos / maxRelativePos) * 100).toFixed(2)}%`;
    return { currentTime, currentTimePos };
  };

  handleMouseDownOrTouchStart = (event: React.MouseEvent | React.TouchEvent): void => {
    event.stopPropagation();
    const { currentTime, currentTimePos } = this.getCurrentProgress(event);

    if (isFinite(currentTime)) {
      this.timeOnMouseMove = currentTime;
      this.setState({
        isDraggingProgress: true,
        currentTimePos,
      });
      if (event.nativeEvent instanceof MouseEvent) {
        window.addEventListener("mousemove", this.handleMouseOrTouchMove);
        window.addEventListener("mouseup", this.handleMouseOrTouchUp);
      }
      else {
        window.addEventListener("touchmove", this.handleMouseOrTouchMove);
        window.addEventListener("touchend", this.handleMouseOrTouchUp);
      }
    }
  };

  handleMouseOrTouchMove = (event: MouseEvent | TouchEvent) => {
    if (event instanceof MouseEvent) {
      event.preventDefault();
    }

    event.stopPropagation();
    const windowSelection: Selection | null = window.getSelection();
    if (windowSelection && windowSelection.type === "Range") {
      windowSelection.empty();
    }
    if (this.state.isDraggingProgress) {
      const { currentTime, currentTimePos } = this.getCurrentProgress(event);
      this.timeOnMouseMove = currentTime;
      this.setState({ currentTimePos });
    }
  };

  handleMouseOrTouchUp = (event: MouseEvent | TouchEvent) => {
    event.stopPropagation();
    this.setState({ isDraggingProgress: false });
    event.stopPropagation();
    const newTime = this.timeOnMouseMove;
    const { audio } = this.props;
    const newProps: { isDraggingProgress: boolean; currentTimePos?: string } = {
      isDraggingProgress: false,
    };
    if (!audio) {
      return;
    }
    if (audio.readyState === audio.HAVE_NOTHING || audio.readyState === audio.HAVE_METADATA || !isFinite(newTime)) {
      newProps.currentTimePos = "0%";
    }
    else {
      audio.currentTime = newTime;
    }

    this.setState(newProps);

    if (event instanceof MouseEvent) {
      window.removeEventListener("mousemove", this.handleMouseOrTouchMove);
      window.removeEventListener("mouseup", this.handleMouseOrTouchUp);
    }
    else {
      window.removeEventListener("touchmove", this.handleMouseOrTouchMove);
      window.removeEventListener("touchend", this.handleMouseOrTouchUp);
    }
  };

  handleAudioTimeUpdate = throttle((e: Event): void => {
    const { isDraggingProgress } = this.state;
    const audio = e.target as HTMLAudioElement;
    if (isDraggingProgress) {
      return;
    }
    const { currentTime } = audio;
    const duration = this.getDuration();

    this.setState({
      currentTimePos: `${((currentTime / duration) * 100 || 0).toFixed(2)}%`,
    });
  }, this.progressUpdateInterval);

  componentDidUpdate(): void {
    const { audio } = this.props;
    if (audio && !this.hasAddedAudioEventListener) {
      this.audio = audio;
      this.hasAddedAudioEventListener = true;
      audio.addEventListener("timeupdate", (e: Event) => {
        this.handleAudioTimeUpdate(e);
      });
    }
  }

  componentWillUnmount(): void {
    if (this.audio && this.hasAddedAudioEventListener) {
      this.audio.removeEventListener("timeupdate", (e: Event) => {
        this.handleAudioTimeUpdate(e);
      });
    }
  }

  render(): React.ReactNode {
    const { progressRef, i18nProgressBar } = this.props;
    const { currentTimePos, isDraggingProgress } = this.state;
    if (!currentTimePos) {
      return null;
    }
    let indicatorClassNames
      = "absolute h-full w-full top-[calc((50%*-1)+1px)] ml-[calc(50%*-1)] box-border rounded-full bg-gray-450 dark:bg-gray-600 shadow shadow-gray-800 dark:shadow-gray-250 ";
    let indicatorContainerClassNames = "absolute z-20 box-border rounded-full h-13/4 aspect-square scale-0 ";
    let progressClassNames = "absolute z-10 box-border rounded-full h-full bg-gray-550 dark:bg-gray-250 ";

    if (isDraggingProgress) {
      indicatorClassNames += "bg-gray-550 dark:bg-gray-250";
      indicatorContainerClassNames += "scale-100";
      progressClassNames += "bg-green-500 dark:bg-green-500";
    }
    else {
      indicatorClassNames += "group-hover:bg-gray-550 dark:group-hover:bg-gray-250";
      indicatorContainerClassNames += "group-hover:scale-100";
      progressClassNames += "group-hover:bg-green-500 dark:group-hover:bg-green-500";
    }
    return (
      <div
        aria-label={i18nProgressBar}
        aria-valuemax={100}
        aria-valuemin={0}
        aria-valuenow={Number(currentTimePos.split("%")[0])}
        className="h-5 w-4/5 flex flex-row flex-1 items-center justify-center group "
        ref={progressRef}
        onMouseDown={this.handleMouseDownOrTouchStart}
        onTouchStart={this.handleMouseDownOrTouchStart}
      >
        <div className="relative box-border rounded-full h-1 w-full bg-gray-450 dark:bg-gray-600 ">
          <div className={indicatorContainerClassNames} style={{ left: currentTimePos }}>
            <div className={indicatorClassNames} />
          </div>
          <div className={progressClassNames} style={{ width: currentTimePos }} />
        </div>
      </div>
    );
  }
}

function ProgressBarForwardRef(props: ProgressBarForwardRefProps, ref: React.Ref<HTMLDivElement>): React.ReactElement {
  return <ProgressBar {...props} progressRef={ref as React.RefObject<HTMLDivElement>} />;
}

export default forwardRef(ProgressBarForwardRef);
export { ProgressBar, ProgressBarForwardRef };
