// src/renderer/src/components/SongArtists.vue
<script setup lang="ts">
import { computed, ref } from "vue";
import { IterationType } from "@/types";
import { useScrollingAnimation } from "@composables/scrollingAnimation";

const props = withDefaults(defineProps<{
  artistNames: string;
  speed?: number;
  pauseAtEndEdgeDurationMs?: number;
  initialMouseIntDelayMs?: number;
  iterationType?: IterationType;
}>(), {
  speed: 0.2,
  pauseAtEndEdgeDurationMs: 1200,
  initialMouseIntDelayMs: 200,
  iterationType: IterationType.SINGLE,
});

const containerRef = ref<HTMLDivElement | null>(null);
const offsetRef = ref<HTMLDivElement | null>(null);
const { handleMouseOver, handleMouseOut } = useScrollingAnimation(
  containerRef,
  offsetRef,
  {
    speed: props.speed,
    pauseAtEndEdgeDurationMs: props.pauseAtEndEdgeDurationMs,
    initialMouseIntDelayMs: props.initialMouseIntDelayMs,
    iterationType: props.iterationType,
  },
);
const artists = computed(() => {
  const artistNames = props.artistNames.split(",");
  const output: string[] = [];
  artistNames.forEach((artistName, index) => {
    output.push(artistName);
    if (index < artistNames.length - 1) {
      output.push(",");
    }
  });
  return output;
});

</script>

<template>
  <div
    class="w-full min-w-0 grid-in-subtitle col-start-badges"
    @blur="handleMouseOut"
    @focus="handleMouseOver"
    @mouseover="handleMouseOver"
    @mouseout="handleMouseOut"
  >
    <div
      ref="containerRef"
      class="relative overflow-hidden -mx-1.5"
      style="mask-image: linear-gradient(90deg, transparent 0, black 6px, black calc(100% - 12px), transparent ); -webkit-mask-image: linear-gradient(90deg, transparent 0, black 6px, black calc(100% - 12px), transparent );"
    >
      <div class="overflow-hidden">
        <div
          ref="offsetRef"
          class="flex w-fit whitespace-nowrap translate-x-[var(--trans-x)] ps-1.5 pe-3"
        >
          <template
            v-for="(artist, index) in artists"
            :key="'artist-name-'+index"
          >
            <span
              v-if="artist === ','"
              class="text-sm font-normal text-gray-800 truncate cursor-default dark:text-gray-200"
            >
              ,&nbsp;
            </span>
            <span
              v-else
              class="text-sm font-normal text-gray-900 truncate cursor-default dark:text-gray-100 hover:underline"
            >
              {{ artist }}
            </span>
          </template>
        </div>
      </div>
    </div>
  </div>
</template>

// src/renderer/src/components/MediaControlsBar/SongDetails/SongArtists/SongArtists.tsx
import React from "react";
import { ScrollingAnimationProps, IterationType } from "@/types";
import useScrollingAnimation from "@renderer/hooks/useScrollingAnimation";

interface SongArtistsProps {
  artistNames: string;
  animationProps?: ScrollingAnimationProps;
}

export default function SongArtists(props: SongArtistsProps) {
  const {
    artistNames,
    animationProps = {
      speed: 0.2,
      pauseAtEndEdgeDurationMs: 1200,
      initialMouseIntDelayMs: 200,
      iterationType: IterationType.single,
    },
  } = props;

  const containerRef = React.useRef<HTMLDivElement>(null);
  const offsetRef = React.useRef<HTMLDivElement>(null);
  const [handleMouseOver, handleMouseOut] = useScrollingAnimation({ containerRef, offsetRef, animationProps });

  const renderArtist = React.useCallback((artist: string, index: number) => {
    return (
      <span
        className="text-sm text-gray-900 dark:text-gray-100 font-normal truncate cursor-default hover:underline"
        key={index}
      >
        {artist}
      </span>
    );
  }, []);

  const renderArtists = React.useCallback(
    (artists: string[]) => {
      const artistsRendered = artists.map(renderArtist);

      const output: JSX.Element[] = [];

      artistsRendered.forEach((artist, index) => {
        output.push(artist);
        if (index < artistsRendered.length - 1) {
          output.push(
            <span
              className="text-sm text-gray-800 dark:text-gray-200 font-normal truncate cursor-default"
              key={`comma-${index}`}
            >
              ,&nbsp;
            </span>
          );
        }
      });

      return output;
    },
    [renderArtist]
  );

  const renderedArtists = React.useMemo(() => renderArtists(artistNames.split(",")), [artistNames, renderArtists]);
  return (
    <div
      className="w-full min-w-0"
      style={{
        gridArea: "subtitle",
        gridColumnStart: "badges",
      }}
      onBlur={handleMouseOut}
      onFocus={handleMouseOver}
      onMouseOut={handleMouseOut}
      onMouseOver={handleMouseOver}
    >
      <div
        ref={containerRef}
        style={{
          marginLeft: "-6px",
          marginRight: "-6px",
          overflow: "hidden",
          position: "relative",
          maskImage: "linear-gradient(90deg, transparent 0, black 6px, black calc(100% - 12px), transparent )",
          // eslint-disable-next-line @typescript-eslint/naming-convention
          WebkitMaskImage: "linear-gradient(90deg, transparent 0, black 6px, black calc(100% - 12px), transparent )",
        }}
      >
        <div className="overflow-hidden">
          <div
            ref={offsetRef}
            style={{
              display: "flex",
              paddingInlineStart: "6px",
              paddingInlineEnd: "12px",
              transform: "translateX(var(--trans-x))",
              whiteSpace: "nowrap",
              width: "fit-content",
            }}
          >
            {renderedArtists}
          </div>
        </div>
      </div>
    </div>
  );
}
