// src/renderer/src/components/MediaControlsBar.vue
<script setup lang="ts">
import { ComponentPublicInstance, computed, onMounted, onUnmounted, ref } from "vue";
import { FilePayload, I18nAriaLabels, RepeatMode } from "@/types";
import PlayButton from "@components/media-controls/PlayButton.vue";
import ProgressBar from "@components/ProgressBar.vue";
import RepeatButton from "@components/media-controls/RepeatButton.vue";
import ShuffleButton from "@components/media-controls/ShuffleButton.vue";
import SkipBackButton from "@components/media-controls/SkipBackButton.vue";
import SkipForwardButton from "@components/media-controls/SkipForwardButton.vue";
import SongArtists from "@components/song-details/SongArtists.vue";
import SongDetails from "@components/song-details/SongDetails.vue";
import SongName from "@components/song-details/SongName.vue";
import { storeToRefs } from "pinia";
import { useAudio } from "@stores/audio";
import { useMediaKeyBindings } from "@stores/mediaKeyBindings";
import VolumeBar from "@components/volume-controls/VolumeBar.vue";
import VolumeButton from "@components/volume-controls/VolumeButton.vue";

const props = withDefaults(defineProps<{
  progressUpdateInterval?: number;
  volumeJumpStep?: number;
  i18nAriaLabels?: I18nAriaLabels;
}>(), {
  progressUpdateInterval: 0,
  volumeJumpStep: 0.05,
  i18nAriaLabels: () => ({
    player: "Audio player",
    progressControl: "Audio progress control",
    volumeControl: "Volume control",
    play: "Play",
    pause: "Pause",
    shuffle: "Enable shuffle",
    shuffleOn: "Disable shuffle",
    previous: "Previous",
    next: "Skip",
    loop: "Enable loop once",
    loopOnce: "Disable loop",
    loopOff: "Enable loop",
    volume: "Mute",
    volumeMute: "Unmute",
  }),
});

const audioStore = useAudio();
const mediaKeyBindingsStore = useMediaKeyBindings();

const { audio, currentTimeDisplay, durationDisplay, isPlaying, shuffle, isMuted, repeatMode } = storeToRefs(audioStore);
const { getNextSong, play, pause, skipPrevious,
  togglePlay, jumpVolume, incrementRepeatMode, toggleMute, toggleShuffle,
  updateCurrentTimeDisplay, updateDurationDisplay } = audioStore;
const { keyBindings } = storeToRefs(mediaKeyBindingsStore);
const { combineKeyCodes } = mediaKeyBindingsStore;


const songName = ref("");
const songArtists = ref("");
const coverArt = ref("");

const container = ref<HTMLDivElement | null>(null);
const progressBarRef = ref<ComponentPublicInstance | null>(null);

const volumeI18n = computed(() => {
  return isMuted ? props.i18nAriaLabels.volumeMute : props.i18nAriaLabels.volume;
});

const playPauseI18n = computed(() => {
  return isPlaying ? props.i18nAriaLabels.pause : props.i18nAriaLabels.play;
});

const shuffleI18n = computed(() => {
  return shuffle ? props.i18nAriaLabels.shuffleOn : props.i18nAriaLabels.shuffle;
});

const repeatI18n = computed(() => {
  switch (repeatMode.value) {
  case RepeatMode.ALL:
    return props.i18nAriaLabels.loop;
  case RepeatMode.ONCE:
    return props.i18nAriaLabels.loopOnce;
  case RepeatMode.NONE:
    return props.i18nAriaLabels.loopOff;
  default:
    return "";
  }
});

function handleKeyDown(event: KeyboardEvent) {
  const keys = combineKeyCodes(event);
  event.preventDefault();
  switch (keys) {
  case keyBindings.value.playPause:
    if (!container.value) {
      return;
    }
    if (!progressBarRef.value) {
      return;
    }
    if (event.target === container.value || event.target === progressBarRef.value.$el) {
      togglePlay();
    }
    break;
  case keyBindings.value.volumeUp:
    jumpVolume(props.volumeJumpStep);
    break;
  case keyBindings.value.volumeDown:
    jumpVolume(-props.volumeJumpStep);
    break;
  case keyBindings.value.repeat:
    incrementRepeatMode();
    break;
  case keyBindings.value.mute:
    toggleMute();
    break;
  case keyBindings.value.shuffle:
    toggleShuffle();
    break;
  case keyBindings.value.jumpForward:
    getNextSong();
    break;
  case keyBindings.value.jumpBackward:
    skipPrevious();
    break;
  default:
    break;
  }
}

function handleFileOpen(_event: Electron.IpcRendererEvent, file: FilePayload) {
  songName.value = file.metadata.common.title ?? "";
  songArtists.value = file.metadata.common.artist ?? "";
  if (file.picture.base64 !== "") {
    coverArt.value = `data:${file.picture.format};base64,${file.picture.base64}`;
  }
  if ("mediaSession" in navigator) {
    const artwork = file.pictures.map((picture) => {
      return {
        src: `data:${file.picture.format};base64,${file.picture.base64}`,
        sizes: picture.dimensions,
        type: picture.format,
      };
    });
    const artist = (() => {
      if (file.metadata.common.artist) {
        const artists = file.metadata.common.artist.split(",");
        if (artists.length > 1) {
          return artists.join(", ");
        }
        return artists[0];
      }
      return "";
    })();

    navigator.mediaSession.metadata = new MediaMetadata({
      title: file.metadata.common.title ?? "",
      artist,
      album: file.metadata.common.album ?? "",
      artwork,
    });
  }
}

onMounted(() => {
  if (!audio.value) {
    return;
  }
  audio.value.addEventListener("ended", getNextSong);
  audio.value.addEventListener("timeupdate", updateCurrentTimeDisplay);
  audio.value.addEventListener("loadedmetadata", updateCurrentTimeDisplay);
  audio.value.addEventListener("durationchange", updateDurationDisplay);
  audio.value.addEventListener("abort", updateDurationDisplay);
  window.api.on("open-file", handleFileOpen);
  if ("mediaSession" in navigator) {
    navigator.mediaSession.setActionHandler("play", play);
    navigator.mediaSession.setActionHandler("pause", pause);
    navigator.mediaSession.setActionHandler("previoustrack", skipPrevious);
    navigator.mediaSession.setActionHandler("nexttrack", getNextSong);
  }
});

onUnmounted(() => {
  if (!audio.value) {
    return;
  }
  audio.value.removeEventListener("ended", getNextSong);
  audio.value.removeEventListener("timeupdate", updateCurrentTimeDisplay);
  audio.value.removeEventListener("loadedmetadata", updateCurrentTimeDisplay);
  audio.value.removeEventListener("durationchange", updateDurationDisplay);
  audio.value.removeEventListener("abort", updateDurationDisplay);
  window.api.off("open-file", handleFileOpen);
});

</script>

<template>
  <div
    ref="container"
    tabindex="0"
    :aria-label="props.i18nAriaLabels.player"
    @keydown="handleKeyDown"
  >
    <div class="flex flex-row items-center justify-between w-full h-full">
      <SongDetails :cover-art="coverArt">
        <template #song-artists>
          <SongArtists :artist-names="songArtists" />
        </template>
        <template #song-name>
          <SongName :song-name="songName" />
        </template>
      </SongDetails>
      <div class="flex w-1/2 min-w-fit max-w-[45rem] flex-col items-center justify-center">
        <div class="flex flex-row items-center w-full gap-3 mb-1 justify-evenly">
          <div class="flex items-center justify-end flex-1 w-full gap-2">
            <ShuffleButton :aria-label="shuffleI18n" />
            <SkipBackButton :aria-label="props.i18nAriaLabels.previous" />
          </div>
          <PlayButton :aria-label="playPauseI18n" />
          <div class="flex items-center justify-start flex-1 w-full gap-2">
            <SkipForwardButton :aria-label="props.i18nAriaLabels.next" />
            <RepeatButton :aria-label="repeatI18n" />
          </div>
        </div>
        <div class="flex flex-row items-center w-full gap-2 justify-evenly">
          <div class="min-w-[2.5rem] text-xs text-gray-800 dark:text-gray-250 text-right">
            {{ currentTimeDisplay }}
          </div>
          <ProgressBar
            ref="progressBarRef"
            :aria-label="props.i18nAriaLabels.progressControl"
            :progress-update-interval="props.progressUpdateInterval"
          />
          <div class="min-w-[2.5rem] text-xs text-gray-800 dark:text-gray-250 text-left">
            {{ durationDisplay }}
          </div>
        </div>
      </div>
      <div class="w-[20%] min-w-[11.25rem] flex flex-row justify-end items-center">
        <div class="flex items-center justify-end flex-grow">
          <div
            class="flex items-center"
            style="flex: 0 1 7.75rem;"
          >
            <VolumeButton :aria-label="volumeI18n" />
            <VolumeBar :aria-label="props.i18nAriaLabels.volumeControl" />
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

// src/renderer/src/components/MediaControlsBar/MediaControlsBar.tsx
import { I18nAriaLabels, FilePayload } from "@/types";
import { TIME_FORMAT } from "@renderer/constants";
// import useForceUpdate from "@renderer/hooks/useForceUpdate";
import React, { ReactNode } from "react";
import MediaControls from "./MediaControls";
import SongDetails from "./SongDetails";
import TrackProgress from "./TrackProgress";
import VolumeControls from "./VolumeControls";
import useQueue from "@renderer/hooks/useQueue";
import useForceUpdate from "@renderer/hooks/useForceUpdate";
import useMediaKeyBindings from "@renderer/hooks/useMediaKeyBindings";
import combineKeyCodes from "@utils/combineKeyCodes";

type MediaControlsBarProps = {
  audio: React.RefObject<HTMLAudioElement>;
  progressUpdateInterval?: number;
  i18nAriaLabels?: I18nAriaLabels;
  defaultCurrentTime?: ReactNode;
  defaultDuration?: ReactNode;
  timeFormat?: TIME_FORMAT;
  volume?: number;
  muted?: boolean;
  expandFunc?: () => void;
  className?: string;
  volumeJumpStep?: number;
};

function MediaControlsBar(props: MediaControlsBarProps): JSX.Element {
  const {
    audio,
    progressUpdateInterval,
    i18nAriaLabels = {
      player: "Audio player",
      progressControl: "Audio progress control",
      volumeControl: "Volume control",
      play: "Play",
      pause: "Pause",
      rewind: "Rewind",
      shuffle: "Shuffle",
      shuffleOn: "Shuffle enabled",
      previous: "Previous",
      next: "Skip",
      loop: "Disable loop",
      loopOnce: "Enable loop once",
      loopOff: "Enable loop",
      volume: "Mute",
      volumeMute: "Unmute",
    },
    defaultCurrentTime = "--:--",
    defaultDuration = "--:--",
    timeFormat = "auto",
    volume = 1,
    muted = false,
    expandFunc,
    className,
    volumeJumpStep = 0.05,
  } = props;

  // const forceUpdate = useForceUpdate();
  const [songName, setSongName] = React.useState("");
  const [artistName, setArtistName] = React.useState("");
  const [coverArt, setCoverArt] = React.useState("");
  const [mediaKeyBindings] = useMediaKeyBindings();
  const forceUpdate = useForceUpdate();

  const [repeat, setRepeat, shuffle, setShuffle, repeatCount, getNextSong, getPreviousSong] = useQueue();

  const lastVolume = React.useRef(volume);
  const container = React.useRef<HTMLDivElement>(null);
  const progressRef = React.useRef<HTMLDivElement>(null);

  const togglePlay = (e: React.SyntheticEvent | Event): void => {
    e.stopPropagation();
    const aud = audio.current;
    if (!aud) {
      return;
    }
    if ((aud.paused || aud.ended) && aud.src) {
      playAudioPromise();
      if ("mediaSession" in navigator) {
        navigator.mediaSession.playbackState = "playing";
      }
    }
    else if (!aud.paused) {
      aud.pause();
      if ("mediaSession" in navigator) {
        navigator.mediaSession.playbackState = "paused";
      }
    }
  };

  const playAudioPromise = (): void => {
    const aud = audio.current;
    if (!aud) {
      return;
    }
    const playPromise = aud.play();
    // playPromise is null in IE 11

    if (repeat === 2 && repeatCount.current > 0) {
      repeatCount.current = 0;
    }

    playPromise.then(null).catch((err) => {
      console.log(err);
    });
  };

  const handleRepeatOnce = (): void => {
    const aud = audio.current;
    const repeatCnt = repeatCount.current;
    if (!aud) {
      return;
    }
    if (repeatCnt === 0) {
      repeatCount.current = 1;
    }
  };

  const handleClickRepeatButton = (): void => {
    const aud = audio.current;
    if (!aud) {
      return;
    }
    if (repeat === 0) {
      aud.loop = true;
      repeatCount.current = 0;
      setRepeat(1);
    }
    else if (repeat === 1) {
      aud.loop = false;
      aud.addEventListener("ended", handleRepeatOnce);
      setRepeat(2);
    }
    else {
      aud.loop = false;
      aud.removeEventListener("ended", handleRepeatOnce);
      setRepeat(0);
      repeatCount.current = 0;
    }
  };

  const handleClickVolumeButton = (): void => {
    const aud = audio.current;
    if (!aud) {
      return;
    }
    if (aud.volume > 0) {
      lastVolume.current = aud.volume;
      aud.volume = 0;
    }
    else {
      aud.volume = lastVolume.current;
    }
  };

  const handleFileOpen = (_event: Electron.IpcRendererEvent, file: FilePayload) => {
    setSongName(file.metadata.common.title ?? "");
    setArtistName(file.metadata.common.artist ?? "");
    if (file.picture.base64 !== "") {
      setCoverArt(`data:${file.picture.format};base64,${file.picture.base64}`);
    }
    if ("mediaSession" in navigator) {
      const artwork = file.pictures.map((picture) => {
        return {
          src: `data:${file.picture.format};base64,${file.picture.base64}`,
          sizes: picture.dimensions,
          type: picture.format,
        };
      });
      const artist = (() => {
        if (file.metadata.common.artist) {
          const artists = file.metadata.common.artist.split(",");
          if (artists.length > 1) {
            return artists.join(", ");
          }
          return artists[0];
        }
        return "";
      })();

      navigator.mediaSession.metadata = new MediaMetadata({
        title: file.metadata.common.title ?? "",
        artist,
        album: file.metadata.common.album ?? "",
        artwork,
      });
    }
  };
  const setJumpVolume = (jumpVolume: number): void => {
    const aud = audio.current;
    if (!aud) {
      return;
    }
    const { volume: prevVolume } = aud;
    if (isFinite(prevVolume)) {
      let volume = prevVolume + jumpVolume;
      volume = Math.round(volume * 100) / 100;
      if (volume < 0) {
        volume = 0;
      }
      else if (volume > 1) {
        volume = 1;
      }
      aud.volume = volume;
    }
  };

  const handleSkipBackward = (): void => {
    const aud = audio.current;
    if (!aud) {
      return;
    }
    const curTime = aud.currentTime * 1000;
    if (curTime < 500) {
      getPreviousSong();
    }
    else {
      aud.currentTime = 0;
    }
  };

  const handleKeyDown = (e: React.KeyboardEvent<HTMLDivElement>): void => {
    const keys = combineKeyCodes(e);
    switch (keys) {
    case mediaKeyBindings.playPause:
      if (!progressRef.current) {
        return;
      }
      if (!container.current) {
        return;
      }
      if (e.target === container.current || e.target === progressRef.current) {
        e.preventDefault();
        togglePlay(e);
      }
      break;
    case mediaKeyBindings.volumeUp:
      e.preventDefault();
      setJumpVolume(volumeJumpStep);
      break;
    case mediaKeyBindings.volumeDown:
      e.preventDefault();
      setJumpVolume(-volumeJumpStep);
      break;
    case mediaKeyBindings.repeat:
      e.preventDefault();
      handleClickRepeatButton();
      break;
    case mediaKeyBindings.mute:
      e.preventDefault();
      handleClickVolumeButton();
      break;
    case mediaKeyBindings.shuffle:
      e.preventDefault();
      setShuffle(!shuffle);
      break;
    default:
      break;
    }
  };

  const addMediaSessionActions = (): void => {
    if (!("mediaSession" in navigator)) {
      return;
    }
    navigator.mediaSession.setActionHandler("play", () => {
      const aud = audio.current;
      if (!aud) {
        return;
      }
      if ((aud.paused || aud.ended) && aud.src) {
        playAudioPromise();
        navigator.mediaSession.playbackState = "playing";
      }
    });
    navigator.mediaSession.setActionHandler("pause", () => {
      const aud = audio.current;
      if (!aud) {
        return;
      }
      if (!aud.paused) {
        aud.pause();
        navigator.mediaSession.playbackState = "paused";
      }
    });
    navigator.mediaSession.setActionHandler("previoustrack", () => {
      handleSkipBackward();
    });
    navigator.mediaSession.setActionHandler("nexttrack", () => {
      getNextSong();
    });
  };

  React.useEffect(() => {
    forceUpdate();
    const aud = audio.current;
    if (!aud) {
      return;
    }
    if (muted) {
      aud.volume = 0;
    }
    else {
      aud.volume = lastVolume.current;
    }
    aud.addEventListener("ended", getNextSong);
    window.api.onFileOpen(handleFileOpen);
    addMediaSessionActions();
    return () => {
      window.api.offFileOpen(handleFileOpen);
      aud.removeEventListener("ended", getNextSong);
    };
  }, []);

  if (!timeFormat) {
    return <></>;
  }
  return (
    <div
      aria-label={i18nAriaLabels?.player}
      className={className}
      ref={container}
      tabIndex={0}
      onKeyDown={handleKeyDown}
    >
      <div className="flex h-full w-full flex-row justify-between items-center">
        <SongDetails artistName={artistName} coverArt={coverArt} expandFunc={expandFunc} songName={songName} />
        <div className="flex w-1/2 min-w-fit max-w-[45rem] flex-col items-center justify-center">
          <MediaControls
            audio={audio.current}
            handleClickRepeatButton={handleClickRepeatButton}
            handleSkipBack={handleSkipBackward}
            handleSkipForward={getNextSong}
            i18nAriaLabels={i18nAriaLabels}
            repeat={repeat}
            setShuffle={setShuffle}
            shuffle={shuffle}
            togglePlay={togglePlay}
          />
          <TrackProgress
            audio={audio.current}
            defaultCurrentTime={defaultCurrentTime}
            defaultDuration={defaultDuration}
            i18nAriaLabels={i18nAriaLabels}
            progressUpdateInterval={progressUpdateInterval}
            ref={progressRef}
            timeFormat={timeFormat}
          />
        </div>
        <div className="w-[20%] min-w-[11.25rem] flex flex-row justify-end items-center">
          <div className="flex flex-grow justify-end items-center">
            <VolumeControls
              audio={audio.current}
              i18nAriaLabels={i18nAriaLabels}
              onClickedVolumeButton={handleClickVolumeButton}
            />
          </div>
        </div>
      </div>
    </div>
  );
}

export default MediaControlsBar;
