// src/renderer/src/components/ProgressBar.vue
<script setup lang="ts">
import { onMounted, onUnmounted, ref } from "vue";
import { MediaReadyState } from "@/types";
import { storeToRefs } from "pinia";
import { useAudio } from "@stores/audio";
import { usePositionX } from "@composables/positionX";
import { useThrottle } from "@composables/throttle";

const props = withDefaults(defineProps<{
  progressUpdateInterval?: number;
}>(), {
  progressUpdateInterval: 0,
});

const { getPositionX } = usePositionX();
const { throttle } = useThrottle();

const { audio, readyState, duration, currentTime, isAudioAvailable } = storeToRefs(useAudio());

const progress = ref<HTMLDivElement | null>(null);
const isDragging = ref(false);
const timeOnMouseMove = ref(0);
const currentTimePosition = ref("0.00%");

function getCurrentProgress(event: MouseEvent | TouchEvent) {
  if (!progress.value) {
    return { currentTimeValue: 0, currentTimePositionValue: "0.00%" };
  }
  const { left, width: maxRelativePosition } = progress.value.getBoundingClientRect();

  const relativePosition = Math.min(Math.max(getPositionX(event) - left, 0), maxRelativePosition);
  const currentTimeValue = (duration.value * relativePosition) / maxRelativePosition;
  const currentTimePositionValue = `${((relativePosition / maxRelativePosition) * 100).toFixed(2)}%`;
  return { currentTimeValue, currentTimePositionValue };
}

function handleMouseOrTouchMove(event: MouseEvent | TouchEvent) {
  if (event instanceof MouseEvent) {
    event.preventDefault();
  }
  event.stopPropagation();
  if (!audio.value) {
    return;
  }

  const windowSelection = window.getSelection();
  if (windowSelection && windowSelection.type === "Range") {
    windowSelection.removeAllRanges();
  }
  if (isDragging.value) {
    const { currentTimeValue, currentTimePositionValue } = getCurrentProgress(event);
    timeOnMouseMove.value = currentTimeValue;
    currentTimePosition.value = currentTimePositionValue;
  }
}

function handleMouseOrTouchUp(event: MouseEvent | TouchEvent) {
  event.stopPropagation();
  isDragging.value = false;
  if (!audio) {
    return;
  }
  if (readyState.value === MediaReadyState.HAVE_NOTHING
    || readyState.value === MediaReadyState.HAVE_METADATA
    || !isFinite(timeOnMouseMove.value)) {
    currentTimePosition.value = "0.00%";
  }
  else {
    currentTime.value = timeOnMouseMove.value;
  }
  if (event instanceof MouseEvent) {
    window.removeEventListener("mousemove", handleMouseOrTouchMove);
    window.removeEventListener("mouseup", handleMouseOrTouchUp);
  }
  else {
    window.removeEventListener("touchmove", handleMouseOrTouchMove);
    window.removeEventListener("touchend", handleMouseOrTouchUp);
  }
}

function handleMouseDownOrTouchStart(event: MouseEvent | TouchEvent) {
  event.stopPropagation();
  if (!audio.value) {
    return;
  }
  isDragging.value = true;
  const { currentTimeValue, currentTimePositionValue } = getCurrentProgress(event);
  if (isFinite(currentTimeValue)) {
    timeOnMouseMove.value = currentTimeValue;
    isDragging.value = true;
    currentTimePosition.value = currentTimePositionValue;
    if (event instanceof MouseEvent) {
      window.addEventListener("mousemove", handleMouseOrTouchMove);
      window.addEventListener("mouseup", handleMouseOrTouchUp);
    }
    else {
      window.addEventListener("touchmove", handleMouseOrTouchMove);
      window.addEventListener("touchend", handleMouseOrTouchUp);
    }
  }
}

const handleAudioTimeUpdate = throttle((_event: Event) => {
  if (isDragging.value) {
    return;
  }
  currentTimePosition.value = `${((currentTime.value / duration.value) * 100).toFixed(2)}%`;
}, props.progressUpdateInterval);

onMounted(() => {
  audio.value?.addEventListener("timeupdate", handleAudioTimeUpdate);
});

onUnmounted(() => {
  audio.value?.removeEventListener("timeupdate", handleAudioTimeUpdate);
});

</script>

<template>
  <div
    v-if="isAudioAvailable"
    ref="progress"
    aria-valuemax="100"
    aria-valuemin="0"
    :aria-valuenow="Number(currentTimePosition.split('%')[0])"
    class="flex flex-row items-center justify-center flex-1 w-4/5 h-5 group"
    role="progressbar"
    @mousedown="handleMouseDownOrTouchStart"
    @touchstart="handleMouseDownOrTouchStart"
  >
    <div class="box-border relative w-full h-1 rounded-full bg-gray-350 dark:bg-gray-750 ">
      <div
        class="box-border absolute z-20 rounded-full h-13/4 aspect-square group-hover:scale-100"
        :class="{ 'scale-100': isDragging, 'scale-0': !isDragging }"
        :style="{ 'left': currentTimePosition }"
      >
        <div
          class="absolute h-full w-full top-[calc((50%*-1)+1px)] ml-[calc(50%*-1)] box-border rounded-full group-hover:bg-gray-550 dark:group-hover:bg-gray-250 shadow shadow-gray-800 dark:shadow-gray-250"
          :class="{ 'bg-gray-550 dark:bg-gray-250': isDragging, 'bg-gray-450 dark:bg-gray-600': !isDragging }"
        />
      </div>
      <div
        class="box-border absolute z-10 h-full rounded-full group-hover:bg-green-700 dark:group-hover:bg-green-600"
        :class="{ 'bg-green-700 dark:bg-green-600': isDragging, 'bg-gray-550 dark:bg-gray-250': !isDragging }"
        :style="{ 'width': currentTimePosition }"
      />
    </div>
  </div>
  <div
    ref="progress"
    class="flex flex-row items-center justify-center flex-1 w-4/5 h-5 group"
    role="progressbar"
  >
    <div class="box-border relative w-full h-1 rounded-full bg-gray-350 dark:bg-gray-750">
      <div class="box-border absolute z-10 h-full bg-gray-300 rounded-full dark:bg-gray-600" />
    </div>
  </div>
</template>

// src/components/MediaControlsBar/TrackProgress/ProgressBar/ProgressBar.tsx
import React, { forwardRef } from "react";
import { getPosX, throttle } from "@/utils";

interface ProgressBarForwardRefProps {
  audio: HTMLAudioElement | null;
  progressUpdateInterval?: number;
  srcDuration?: number;
  i18nProgressBar?: string;
  style?: React.CSSProperties;
}

interface ProgressBarProps extends ProgressBarForwardRefProps {
  progressRef: React.RefObject<HTMLDivElement>;
}

interface TimePosInfo {
  currentTime: number;
  currentTimePos: string;
}

function ProgressBar({
  audio,
  progressUpdateInterval = 0,
  srcDuration,
  i18nProgressBar,
  style,
  progressRef,
}: ProgressBarProps): JSX.Element {
  const hasAddedAudioEventListener = React.useRef(false);
  const isDraggingProgress = React.useRef(false);
  const [isDragging, setIsDragging] = React.useState(isDraggingProgress.current);
  const timeOnMouseMove = React.useRef(0);
  const [currentTimePos, setCurrentTimePos] = React.useState("0.00%");

  const getDuration = React.useCallback((): number => {
    if (!audio) {
      return 0;
    }
    return typeof srcDuration === "undefined" ? audio.duration : srcDuration;
  }, [audio, srcDuration]);

  const getCurrentProgress = React.useCallback(
    (event: MouseEvent | React.MouseEvent | TouchEvent | React.TouchEvent): TimePosInfo => {
      if (!progressRef.current) {
        return { currentTime: 0, currentTimePos: "0%" };
      }
      const rect = progressRef.current.getBoundingClientRect();
      const maxRelativePos = rect.width;

      let relativePos = getPosX(event) - rect.left;

      if (relativePos < 0) {
        relativePos = 0;
      }
      else if (relativePos > maxRelativePos) {
        relativePos = maxRelativePos;
      }
      const duration = getDuration();
      const currentTime = (duration * relativePos) / maxRelativePos;
      const currentTimePos = `${((relativePos / maxRelativePos) * 100).toFixed(2)}%`;
      return { currentTime, currentTimePos };
    },
    [getDuration, progressRef]
  );

  const handleMouseOrTouchMove = (event: MouseEvent | TouchEvent) => {
    if (event instanceof MouseEvent) {
      event.preventDefault();
    }

    event.stopPropagation();
    const windowSelection: Selection | null = window.getSelection();
    if (windowSelection && windowSelection.type === "Range") {
      windowSelection.empty();
    }
    if (isDraggingProgress.current) {
      const { currentTime, currentTimePos } = getCurrentProgress(event);
      timeOnMouseMove.current = currentTime;
      setCurrentTimePos(currentTimePos);
    }
  };

  const handleMouseOrTouchUp = (event: MouseEvent | TouchEvent) => {
    event.stopPropagation();
    isDraggingProgress.current = false;
    setIsDragging(isDraggingProgress.current);
    const newTime = timeOnMouseMove.current;
    if (!audio) {
      return;
    }
    if (audio.readyState === audio.HAVE_NOTHING || audio.readyState === audio.HAVE_METADATA || !isFinite(newTime)) {
      setCurrentTimePos("0.00%");
    }
    else {
      audio.currentTime = newTime;
    }
    if (event instanceof MouseEvent) {
      window.removeEventListener("mousemove", handleMouseOrTouchMove);
      window.removeEventListener("mouseup", handleMouseOrTouchUp);
    }
    else {
      window.removeEventListener("touchmove", handleMouseOrTouchMove);
      window.removeEventListener("touchend", handleMouseOrTouchUp);
    }
  };

  const handleMouseDownOrTouchStart = (event: React.MouseEvent | React.TouchEvent) => {
    event.stopPropagation();
    const { currentTime, currentTimePos } = getCurrentProgress(event);
    if (isFinite(currentTime)) {
      timeOnMouseMove.current = currentTime;
      isDraggingProgress.current = true;
      setIsDragging(isDraggingProgress.current);
      setCurrentTimePos(currentTimePos);
      if (event.nativeEvent instanceof MouseEvent) {
        window.addEventListener("mousemove", handleMouseOrTouchMove);
        window.addEventListener("mouseup", handleMouseOrTouchUp);
      }
      else {
        window.addEventListener("touchmove", handleMouseOrTouchMove);
        window.addEventListener("touchend", handleMouseOrTouchUp);
      }
    }
  };

  const handleAudioTimeUpdate = throttle((e: Event): void => {
    const audio = e.target as HTMLAudioElement;
    if (isDraggingProgress.current) {
      return;
    }
    const { currentTime } = audio;
    const duration = getDuration();
    const currentTimePos = `${((currentTime / duration) * 100).toFixed(2)}%`;
    setCurrentTimePos(currentTimePos);
  }, progressUpdateInterval);

  React.useEffect(() => {
    if (audio && !hasAddedAudioEventListener.current) {
      audio.addEventListener("timeupdate", handleAudioTimeUpdate);
      hasAddedAudioEventListener.current = true;
    }
    return () => {
      if (audio && hasAddedAudioEventListener.current) {
        audio.removeEventListener("timeupdate", handleAudioTimeUpdate);
        hasAddedAudioEventListener.current = false;
      }
    };
  }, [audio, handleAudioTimeUpdate]);

  if (!currentTimePos) {
    return <></>;
  }
  return (
    <div
      aria-label={i18nProgressBar}
      aria-valuemax={100}
      aria-valuemin={0}
      aria-valuenow={Number(currentTimePos.split("%")[0])}
      className="h-5 w-4/5 flex flex-row flex-1 items-center justify-center group "
      ref={progressRef}
      style={style}
      onMouseDown={handleMouseDownOrTouchStart}
      onTouchStart={handleMouseDownOrTouchStart}
    >
      <div className="relative box-border rounded-full h-1 w-full bg-gray-450 dark:bg-gray-600 ">
        <div
          style={{ left: currentTimePos }}
          className={`absolute z-20 box-border rounded-full h-13/4 aspect-square group-hover:scale-100 ${
            isDragging ? "scale-100" : "scale-0"
          }`}
        >
          <div
            className={`absolute h-full w-full top-[calc((50%*-1)+1px)] ml-[calc(50%*-1)] box-border rounded-full group-hover:bg-gray-550 dark:group-hover:bg-gray-250 shadow shadow-gray-800 dark:shadow-gray-250 ${
              isDragging ? "bg-gray-550 dark:bg-gray-250" : "bg-gray-450 dark:bg-gray-600"
            }`}
          />
        </div>
        <div
          style={{ width: currentTimePos }}
          className={`absolute z-10 box-border rounded-full h-full group-hover:bg-green-500 dark:group-hover:bg-green-500 ${
            isDragging ? "bg-green-500 dark:bg-green-500" : "bg-gray-550 dark:bg-gray-250"
          }`}
        />
      </div>
    </div>
  );
}

function ProgressBarForwardRef(props: ProgressBarForwardRefProps, ref: React.Ref<HTMLDivElement>): React.ReactElement {
  return <ProgressBar {...props} progressRef={ref as React.RefObject<HTMLDivElement>} />;
}

export default forwardRef(ProgressBarForwardRef);
export { ProgressBar, ProgressBarForwardRef };
